package com.gestionStock.backend.service.parametre;

import com.gestionStock.backend.entity.entreprise.Entreprise;
import com.gestionStock.backend.entity.parametre.DocumentDisplaySetting;
import com.gestionStock.backend.entity.parametre.DocumentType;
import com.gestionStock.backend.repository.parametre.DocumentDisplaySettingRepository;
import com.gestionStock.backend.service.user.UserService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import org.springframework.jdbc.core.JdbcTemplate;
import jakarta.annotation.PostConstruct;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Transactional
public class DocumentDisplaySettingService {

    private final DocumentDisplaySettingRepository repository;
    private final UserService userService;
    private final JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void syncSequence() {
        try {
            // Drop outdated check constraint generated by Hibernate for the DocumentType
            // enum
            jdbcTemplate.execute(
                    "ALTER TABLE document_display_setting DROP CONSTRAINT IF EXISTS document_display_setting_document_type_check");
            // Sync sequence
            jdbcTemplate.execute(
                    "SELECT setval('document_display_setting_id_seq', COALESCE((SELECT MAX(id)+1 FROM document_display_setting), 1), false)");
        } catch (Exception e) {
            System.err.println("Ignored sequence/constraint sync: " + e.getMessage());
        }
    }

    public List<DocumentDisplaySetting> getAllSettingsForCurrentEntreprise() {
        Entreprise entreprise = userService.getCurrentUserEntreprise();
        if (entreprise == null)
            return List.of();
        return repository.findByEntrepriseId(entreprise.getId());
    }

    public DocumentDisplaySetting getOrCreateSettingByType(DocumentType type) {
        Entreprise entreprise = userService.getCurrentUserEntreprise();
        if (entreprise == null)
            throw new IllegalStateException("Entreprise non identifiée");

        return repository.findByEntrepriseIdAndDocumentType(entreprise.getId(), type)
                .orElseGet(() -> {
                    DocumentDisplaySetting ds = DocumentDisplaySetting.builder()
                            .documentType(type)
                            .entreprise(entreprise)
                            .primaryColor("#0D9488")
                            .secondaryColor("#1e293b")
                            .showLogo(true)
                            .showSignatureMagasinier(true)
                            .showSignatureClient(true)
                            .layout("MODERN")
                            .fontSize("MEDIUM")
                            .showPriceHT(true)
                            .showTVA(true)
                            .showDiscount(true)
                            .visibleVarianteIds(new java.util.ArrayList<>())
                            .build();
                    return ds;
                });
    }

    public DocumentDisplaySetting saveSetting(DocumentDisplaySetting setting) {
        Entreprise entreprise = userService.getCurrentUserEntreprise();
        if (entreprise == null)
            throw new IllegalStateException("Entreprise non identifiée");

        setting.setEntreprise(entreprise);

        try {
            return repository.findByEntrepriseIdAndDocumentType(entreprise.getId(), setting.getDocumentType())
                    .map(existing -> {
                        existing.setPrimaryColor(setting.getPrimaryColor());
                        existing.setSecondaryColor(setting.getSecondaryColor());
                        existing.setShowLogo(setting.getShowLogo());
                        existing.setShowSignatureMagasinier(setting.getShowSignatureMagasinier());
                        existing.setShowSignatureClient(setting.getShowSignatureClient());
                        existing.setFooterText(setting.getFooterText());
                        existing.setLayout(setting.getLayout());
                        existing.setFontSize(setting.getFontSize());
                        existing.setShowPriceHT(setting.getShowPriceHT());
                        existing.setShowTVA(setting.getShowTVA());
                        existing.setShowDiscount(setting.getShowDiscount());
                        existing.setVisibleVarianteIds(setting.getVisibleVarianteIds());
                        return repository.save(existing);
                    })
                    .orElseGet(() -> repository.save(setting));
        } catch (Exception e) {
            System.err.println("ERREUR GRAVE LORS DU SAVE DE CONFIG DOCUMENT : " + setting.getDocumentType());
            e.printStackTrace();
            throw e;
        }
    }

    public void initializeDefaults(Entreprise entreprise) {
        for (DocumentType type : DocumentType.values()) {
            if (repository.findByEntrepriseIdAndDocumentType(entreprise.getId(), type).isEmpty()) {
                DocumentDisplaySetting defaultSetting = DocumentDisplaySetting.builder()
                        .entreprise(entreprise)
                        .documentType(type)
                        .primaryColor("#0D9488")
                        .secondaryColor("#1e293b")
                        .showLogo(true)
                        .showSignatureMagasinier(true)
                        .showSignatureClient(true)
                        .layout("MODERN")
                        .fontSize("MEDIUM")
                        .showPriceHT(true)
                        .showTVA(true)
                        .showDiscount(true)
                        .build();
                repository.save(defaultSetting);
            }
        }
    }
}
