package com.gestionStock.backend.entity.Stock;

public enum TypeMouvement {
	SORTIE_VENTE, SORTIE_PERTE, SORTIE_MAINTENANCE, ENTREE_RETOUR, ENTREE_RECEPTION, SORTIE_RETOUR,
	ENTREE_INVENTAIRE, SORTIE_INVENTAIRE
}
